# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZjY4NDFhMGUxYmQzOGI5YmJhMDExOWJiODdhYjdiNDNjZGFmNmRkNTBiYTliY2ZjNmZhZGQxMzE0NjdkOWZkOWE5OTE0NzA1NWI4ZjRkNDRhNTc2OTRmZTkxMTZkOGY1MmU1YmVhNmJhMzdlMWMzNDVkYTM1ZGMxZTQ5ZTc3NWY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
